name: CV of CHEN Han

on: [push]

jobs:
  awesome-cv-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses:  wsoula/Awesome-CV-action@v0.0.2
      with:
        FILE_NAME: 'latex/resume.tex'
